require:
  - rubocop-rails

AllCops:
  Exclude:
    - Gemfile*
    - bin/*
    - gemfiles/**/*
    - vendor/bundle/**/*
  # Automatically enables new cops so that we only have to add them to
  # edit default behavior
  NewCops: enable

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude: ["test/**/*"]

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Exclude: ["devise-security.gemspec"]

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

Style/SymbolArray:
  EnforcedStyle: brackets

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

# TODO can this be removed
Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  # They read better, more like normal English.
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
