require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  Exclude:
    - gemfiles/**/*
    - vendor/bundle/**/*
  # Automatically enables new cops so that we only have to add them to
  # edit default behavior
  NewCops: enable

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude: ["test/**/*"]

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Exclude: ["devise-security.gemspec"]

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
