version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - bundle-data:/usr/local/bundle

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - default

    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongodb/mongodb-community-server
    restart: unless-stopped
    networks:
      - default
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: mongodb
      MONGODB_INITDB_ROOT_PASSWORD: mongodb

  postgres:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  default:

volumes:
  bundle-data:
  mongodb-data:
  postgres-data:
